variables:
  K8S_API_URL: https://158.160.109.92
  DOCKER_REGISTRY: s015605.gitlab.yandexcloud.net/
  DOCKER_USERNAME: $CI_REGISTRY_USER
  DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
  FRONTEND_NAME: yelb-ui
  BACKEND_NAME: yelb-appserver
  APP_NAME:  yelb


stages:
  - build
  - test
  - cleanup
  - push
  - deploy

build:backend:
  stage: build
  image: docker:latest
  script:
    - cd $BACKEND_NAME
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$BACKEND_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID .

build:frontend:
  stage: build
  image: docker:latest
  script:
    - cd $FRONTEND_NAME
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$FRONTEND_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID .

test:
  stage: test
  image:
    name: docker/compose:1.23.2
    entrypoint: [""]
  script:
    - docker-compose 
        -p "$CI_PROJECT_NAME"_"$CI_PIPELINE_ID"
      up
        --abort-on-container-exit
        --exit-code-from test
        --quiet-pull

cleanup:
  stage: cleanup
  image:
    name: docker/compose:1.23.2
    entrypoint: [""]
  script:
    - docker-compose -p "$CI_PROJECT_NAME"_"$CI_PIPELINE_ID" down
  when: always

push:
  image: docker:latest
  stage: push
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$BACKEND_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$FRONTEND_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  only:
    - main

deploy:
  stage: deploy
  image: centosadmin/kubernetes-helm:latest
  environment:
    name: production
  variables:
    KUBECONFIG: /tmp/.kubeconfig

  script:
    - kubectl config set-cluster k8s --insecure-skip-tls-verify=true --server=$K8S_API_URL
    - kubectl config set-credentials admin --token=$K8S_CI_TOKEN
    - kubectl config set-context default --cluster=k8s --user=admin
    - kubectl config use-context default
    - kubectl cluster-info
    - helm upgrade --install $APP_NAME .helm
        --set yelbappserver.image=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$BACKEND_NAME
        --set yelbappserver.imageTag=$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
        --set yelbappserver.env.YELB_DB_SERVER_ENDPOINT=rc1a-y748ih7sfsdthow9.mdb.yandexcloud.net
        --set yelbappserver.env.YELB_DB_SERVER_USER=yelbduser
        --set yelbappserver.env.YELB_DB_SERVER_PASSWORD=yelbduser
        --set yelbappserver.env.YELB_DB_NAME=yelbdatabase
        --set yelbappserver.env.RACK_ENV=production
        --set yelbui.image=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$BACKEND_NAME
        --set yelbui.imageTag=$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
        --set yelbui.env.UI_ENV=prod
        --wait
        --timeout 300s
        --atomic
        --debug
        --namespace $APP_NAME-$CI_ENVIRONMENT_NAME
  only:
    - main