#use this with `docker-compose up` against a generic Docker end-point (e.g. standalone Docker)
version: "3"
services:
  yelb-ui:
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$FRONTEND_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
    depends_on:
      - yelb-appserver
    ports:
      - 8080:80
    environment:
      - UI_ENV=test # dev | test | prod 
      

  yelb-appserver:
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$BACKEND_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
    depends_on:
      - redis-server
      - yelb-db
    ports:
      - 4567:4567
    environment:
      - RACK_ENV=test # development | test | production 

  redis-server:
    image: redis:4.0.2
    ports:
      - 6379:6379

  yelb-db:
    image: yelb-db:0.5
    ports:
      - 5432:5432

  test:
    image: curlimages/curl:7.73.0
    command: /bin/sh -c "sleep 10 && curl -s http://yelb-ui:80/ -i -vvv"

