apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.yelbui.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"

  name: {{ .Values.yelbui.name }}
spec:
  rules:

    - host: {{ .Values.yelbui.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.yelbui.name }}
                port:
                  number: {{ .Values.yelbui.service.port }}
  tls:
    - hosts:
      - {{ .Values.yelbui.ingress.host }}
      secretName: {{ .Values.yelbui.ingress.host }}



