# This is a YAML-formatted file.

image: s015605.gitlab.yandexcloud.net:5050/etern0/graduation_work/yelb-ui
imageTag: main.93
imagePullSecret: k8s-docker

# Resources for app. Limits is the maximum number of resources that app cas use.
# And requests is resources that will be granted to the app at start time.
yelbui:
  name: yelb-ui
  image: s015605.gitlab.yandexcloud.net:5050/etern0/graduation_work/yelb-ui
  imageTag: main.107
  imagePullSecret: k8s-docker
  replicas: 3

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

  service:
    app_port: 80
    port: 80

  ingress:
    host: s015605.site
  
  env:
    UI_ENV: prod


yelbappserver:
  name: yelb-appserver
  image: s015605.gitlab.yandexcloud.net:5050/etern0/graduation_work/yelb-appserver
  imageTag: main.107
  imagePullSecret: k8s-docker
  replicas: 3

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

  service:
    app_port: 4567
    port: 4567

  env:
    YELB_DB_SERVER_ENDPOINT: rc1a-y748ih7sfsdthow9.mdb.yandexcloud.net
    YELB_DB_SERVER_PORT: 6432
    YELB_DB_SERVER_USER: yelbduser
    YELB_DB_SERVER_PASSWORD: yelbduser
    YELB_DB_NAME: yelbdatabase
    RACK_ENV: production


redis:
  name: redis-server
  image: redis
  imageTag: 4.0.2
  replicas: 1

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

  service:
    port: 6379
